import { expect,test } from "@playwright/test";
import { credential } from "../test-credentials";
async function login(page:import("@playwright/test").Page,label:string){const auth=credential(label)!;await page.goto("/login");await page.getByLabel("Email").fill(auth.email);await page.getByLabel("Password").fill(auth.password);await page.getByRole("button",{name:/sign in/i}).click();await expect(page).toHaveURL(/\/app/)}
test("unauthenticated protected route redirects to login",async({page})=>{await page.goto("/app");await expect(page).toHaveURL(/\/login/);await expect(page.getByRole("heading",{name:"Welcome back."})).toBeVisible()});
test("login never places password in URL",async({page})=>{await page.goto("/login");await page.getByLabel("Email").fill("unknown@example.com");await page.getByLabel("Password").fill("NeverInUrl12");await page.getByRole("button",{name:/sign in/i}).click();await expect(page).not.toHaveURL(/NeverInUrl12/)});
test("recovery validates email in browser",async({page})=>{await page.goto("/forgot-password");await page.getByLabel("Email").fill("not-an-email");await page.getByRole("button",{name:/send reset/i}).click();await expect(page.getByLabel("Email")).toHaveJSProperty("validity.valid",false)});
test("Super Admin opens staff and roles then logs out",async({page})=>{await login(page,"SUPER_ADMIN");await page.goto("/app/staff");await expect(page.getByRole("heading",{name:"Staff"})).toBeVisible();await page.goto("/app/roles");await expect(page.getByRole("heading",{name:"Roles & permissions"})).toBeVisible();await page.getByRole("button",{name:/sign out/i}).click();await page.goto("/app");await expect(page).toHaveURL(/\/login/)});
test("Accountant cannot open role management",async({page})=>{await login(page,"ACCOUNTANT");await page.goto("/app/roles");await expect(page.getByRole("heading",{name:"Access denied"})).toBeVisible()});
test("Customer cannot open staff management",async({page})=>{await login(page,"CUSTOMER_A");await page.goto("/app/staff");await expect(page.getByRole("heading",{name:"Access denied"})).toBeVisible()});
