create extension if not exists pgcrypto;
create type public.app_role as enum ('super_admin','admin','manager','sales_executive','installation_staff','service_technician','accountant','customer');
create type public.lead_status as enum ('New','Contacted','Follow-up','Site Visit Scheduled','Site Visit Completed','Quotation Sent','Negotiation','Won','Lost','On Hold');

create table public.roles (id uuid primary key default gen_random_uuid(), name public.app_role unique not null, description text, created_at timestamptz not null default now());
create table public.permissions (id uuid primary key default gen_random_uuid(), key text unique not null check (key ~ '^[a-z_]+:[a-z_]+$'), description text);
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, phone text, active boolean not null default true, branch_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_roles (user_id uuid references public.profiles(id) on delete cascade, role_id uuid references public.roles(id) on delete cascade, primary key(user_id,role_id));
create table public.role_permissions (role_id uuid references public.roles(id) on delete cascade, permission_id uuid references public.permissions(id) on delete cascade, primary key(role_id,permission_id));
create table public.branches (id uuid primary key default gen_random_uuid(), name text not null, code text unique not null, active boolean not null default true, created_at timestamptz not null default now());
alter table public.profiles add constraint profiles_branch_fk foreign key(branch_id) references public.branches(id);

create table public.leads (
 id uuid primary key default gen_random_uuid(), lead_number text unique not null, customer_name text not null, mobile text not null check(mobile ~ '^[6-9][0-9]{9}$'),
 email text, city text, customer_type text not null check(customer_type in ('Residential','Commercial','Industrial')), monthly_bill numeric(14,2) check(monthly_bill>=0),
 capacity_kw numeric(12,3) check(capacity_kw>0), source text not null, priority text not null default 'Medium' check(priority in ('Low','Medium','High','Urgent')),
 status public.lead_status not null default 'New', assigned_to uuid references public.profiles(id), next_followup_at timestamptz, notes text,
 lost_reason text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create index leads_status_idx on public.leads(status); create index leads_assigned_idx on public.leads(assigned_to); create index leads_mobile_idx on public.leads(mobile);
create table public.lead_activities (id uuid primary key default gen_random_uuid(), lead_id uuid not null references public.leads(id) on delete cascade, activity_type text not null, notes text, next_followup_at timestamptz, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.customers (id uuid primary key default gen_random_uuid(), customer_number text unique not null, profile_id uuid unique references public.profiles(id), name text not null, customer_type text not null, mobile text not null, email text, gst_number text, consumer_number text, provider text, status text not null default 'Active', assigned_to uuid references public.profiles(id), created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.customer_addresses (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, address_type text not null check(address_type in ('Billing','Installation')), line1 text not null, city text, district text, state text, pin_code text check(pin_code is null or pin_code ~ '^[1-9][0-9]{5}$'));
create table public.products (id uuid primary key default gen_random_uuid(), sku text unique not null, name text not null, category text not null, brand text, model text, unit text not null, purchase_price numeric(14,2) not null default 0, selling_price numeric(14,2) not null default 0, tax_rate numeric(5,2) not null default 0, minimum_stock numeric(14,3) not null default 0, active boolean not null default true, created_at timestamptz not null default now());
create table public.inventory_transactions (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id), transaction_type text not null check(transaction_type in ('IN','OUT','ADJUSTMENT','ISSUE','RETURN')), quantity numeric(14,3) not null check(quantity<>0), reference_type text, reference_id uuid, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.quotations (id uuid primary key default gen_random_uuid(), quotation_number text unique not null, customer_id uuid not null references public.customers(id), lead_id uuid references public.leads(id), quotation_date date not null, valid_until date not null, capacity_kw numeric(12,3) not null, status text not null default 'Draft', subtotal numeric(14,2) not null default 0, discount numeric(14,2) not null default 0, tax numeric(14,2) not null default 0, grand_total numeric(14,2) not null default 0, terms text, created_by uuid references public.profiles(id), approved_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.quotation_items (id uuid primary key default gen_random_uuid(), quotation_id uuid not null references public.quotations(id) on delete cascade, product_id uuid references public.products(id), description text not null, quantity numeric(14,3) not null check(quantity>0), unit_price numeric(14,2) not null check(unit_price>=0), tax_rate numeric(5,2) not null default 0);
create table public.projects (id uuid primary key default gen_random_uuid(), project_number text unique not null, customer_id uuid not null references public.customers(id), quotation_id uuid unique references public.quotations(id), capacity_kw numeric(12,3) not null, stage text not null default 'Confirmed', progress smallint not null default 0 check(progress between 0 and 100), project_value numeric(14,2) not null default 0, start_date date, expected_completion_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.invoices (id uuid primary key default gen_random_uuid(), invoice_number text unique not null, customer_id uuid not null references public.customers(id), project_id uuid references public.projects(id), invoice_date date not null, due_date date not null, total numeric(14,2) not null check(total>=0), paid_amount numeric(14,2) not null default 0 check(paid_amount>=0), status text not null default 'Draft', created_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(), payment_number text unique not null, customer_id uuid not null references public.customers(id), invoice_id uuid references public.invoices(id), payment_date date not null, amount numeric(14,2) not null check(amount>0), method text not null, transaction_reference text, recorded_by uuid references public.profiles(id), reversed_at timestamptz, created_at timestamptz not null default now());
create table public.service_tickets (id uuid primary key default gen_random_uuid(), ticket_number text unique not null, customer_id uuid not null references public.customers(id), project_id uuid references public.projects(id), subject text not null, description text not null, priority text not null default 'Medium', status text not null default 'Open', assigned_to uuid references public.profiles(id), resolution text, opened_at timestamptz not null default now(), closed_at timestamptz);
create table public.documents (id uuid primary key default gen_random_uuid(), original_name text not null, storage_path text unique not null, mime_type text not null, file_size bigint not null check(file_size>0), uploaded_by uuid not null references public.profiles(id), entity_type text not null, entity_id uuid not null, category text not null, created_at timestamptz not null default now());
create table public.website_enquiries (id uuid primary key default gen_random_uuid(), name text not null, mobile text not null, email text, enquiry_type text not null, message text, status text not null default 'New', created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_user_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, old_values jsonb, new_values jsonb, ip_address inet, user_agent text, created_at timestamptz not null default now());

create function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at();
create trigger leads_touch before update on public.leads for each row execute function public.touch_updated_at();
create trigger customers_touch before update on public.customers for each row execute function public.touch_updated_at();

create function public.has_role(required public.app_role) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from user_roles ur join roles r on r.id=ur.role_id where ur.user_id=auth.uid() and r.name=required) $$;
alter table public.profiles enable row level security; alter table public.leads enable row level security; alter table public.customers enable row level security;
alter table public.quotations enable row level security; alter table public.projects enable row level security; alter table public.invoices enable row level security;
alter table public.payments enable row level security; alter table public.service_tickets enable row level security; alter table public.documents enable row level security;
alter table public.notifications enable row level security; alter table public.audit_logs enable row level security; alter table public.website_enquiries enable row level security;
create policy profiles_self_read on public.profiles for select using(id=auth.uid() or public.has_role('super_admin'));
create policy customer_self_read on public.customers for select using(profile_id=auth.uid() or public.has_role('super_admin') or public.has_role('admin'));
create policy quotation_customer_read on public.quotations for select using(exists(select 1 from public.customers c where c.id=customer_id and c.profile_id=auth.uid()) or public.has_role('super_admin') or public.has_role('admin'));
create policy project_customer_read on public.projects for select using(exists(select 1 from public.customers c where c.id=customer_id and c.profile_id=auth.uid()) or public.has_role('super_admin') or public.has_role('admin'));
create policy invoice_customer_read on public.invoices for select using(exists(select 1 from public.customers c where c.id=customer_id and c.profile_id=auth.uid()) or public.has_role('super_admin') or public.has_role('admin') or public.has_role('accountant'));
create policy notification_owner on public.notifications for select using(user_id=auth.uid());
create policy public_enquiry_insert on public.website_enquiries for insert to anon with check(length(name) between 2 and 120 and mobile ~ '^[6-9][0-9]{9}$');
revoke delete, update on public.audit_logs from authenticated;
